/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_danielsierraf_read4me_MainActivity */

#ifndef _Included_com_example_danielsierraf_read4me_MainActivity
#define _Included_com_example_danielsierraf_read4me_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_danielsierraf_read4me_MainActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_danielsierraf_read4me_MainActivity_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
